---
- name: "Common | set os specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_os_family }}.yml"
    - "os-default.yml"

  tags:
    - always

- name: "Install packages"
  ansible.builtin.include_tasks: packages-{{ ansible_os_family }}.yml
  tags:
    - unbound
    - unbound:packages
  when: unbound_supported

- name: "Configure unbound"
  ansible.builtin.include_tasks: common-config.yml
  tags:
    - unbound
    - unbound:config
  when: unbound_supported

- name: "Set systemd service"
  ansible.builtin.include_tasks: common-service.yml
  tags:
    - unbound
    - unbound:setup
  when: unbound_supported

